
const ACTIONS_TYPES = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',


    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    SAVE_MANUAL_USER_EXPENSE_DATA_REQUEST: 'SAVE_MANUAL_USER_EXPENSE_DATA_REQUEST',
    SAVE_MANUAL_USER_EXPENSE_DATA_SUCCESS: 'SAVE_MANUAL_USER_EXPENSE_DATA_SUCCESS',
    SAVE_MANUAL_USER_EXPENSE_DATA_FAILURE: 'SAVE_MANUAL_USER_EXPENSE_DATA_FAILURE',

    GET_USER_EXPENSE_DATA_REQUEST: 'GET_USER_EXPENSE_DATA_REQUEST',
    GET_USER_EXPENSE_DATA_SUCCESS: 'GET_USER_EXPENSE_DATA_SUCCESS',
    GET_USER_EXPENSE_DATA_FAILURE: 'GET_USER_EXPENSE_DATA_FAILURE',
    
    
}

export default ACTIONS_TYPES